### ISSUE TITLE
[FLTR]: Install Location

### ISSUE THREAD

**Issue by few23** [Tormak9970/TabMaster#126] opened 2023-10-09 06:15 UTC
Be able to make a Tab for Installed on SD Card. Name for the tab corresponds to label of SD Card, so you can know what's installed on which different SD card.

**Comment by Tormak9970** [comment] 2023-12-07 15:59
Closing as this is a duplicate of #92. We're planning on implementing this feature though

**Closed by Tormak9970** 2023-12-07 15:59 UTC
Labels: filter
