### ISSUE TITLE
[BUG]: Error Reference: Shared SteamUI_8145392_6726dc67997779fd, Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by e-minguez** [Tormak9970/TabMaster#66] opened 2023-07-11 07:58 UTC
**Describe the bug**
After installing Tab Master I cannot longer access steam settings.

**To Reproduce**
1. Install TabMaster
2. Press the Steam button -> Settings
3. See error

**Expected behavior**
Everything works

**Screenshots**
![](https://i.redd.it/d1ut9xmj5lab1.png)

**Logs**:
Sorry, I don't have logs as the workaround is to remove TabMaster. There is also a Reddit thread with some other folks having the same issue -> https://www.reddit.com/r/SteamDeck/comments/14tf4b8/

**Enviroment Info:**
 - SteamOS Version [3.4.8]
 - SteamOS Update Channel [Stable]
 - Decky Version [2.10.3]
 - Decky Update Channel [Stable]
 - TabMaster Version [1.2.0]

I think this is probably related to some combination of decky plugins. Just in case my list of installed plugins is:

* vibrantdeck - 1.4.0
* DeckFAQs - 1.7.1
* AutoFlatpaks - 1.6.5
* HLTB for deck - 1.3.1
* SteamGridDB - 1.2.5
* PowerTools - 1.3.2
* ControllerTools - 1.1.2-1
* Bluetooth - 2.0.4
* Tailscale control - 0.0.4
* Animation Changer - 1.3.0-1
* CSS Loader - 1.7.1
* Network Info - 1.0.0.1

For CSS loader the following themes are applied:
* Clean Gameview 1.3
* Round 2.4
* Switch Like Home 1.2
* Top Bar Transpacency 1.0

**Comment by Tormak9970** [comment] 2023-07-11 13:17
This os caused by having no hidden games iirc. Its been fixed in the update that's under review (1.3.0). You can grab it from github if you want it early.

**Comment by Tormak9970** [comment] 2023-07-11 16:43
Added a comment on the reddit thread explaining that as well. closing this as it has already been fixed

**Closed by Tormak9970** 2023-07-11 16:43 UTC
Labels: bug
